backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: vweltje/vweltje # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: 23c5658658ffad7df124
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  # ----------------------------------------------------------------------------
  # Pages
  # ----------------------------------------------------------------------------
  - name: 'pages'
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      #
      # Landingpage
      #
      - file: 'content/pages/landing.md'
        label: 'Landingpage'
        name: 'landing-page'
        fields:
          - label: 'Hero'
            required: true
            name: 'hero'
            widget: 'object'
            fields:
              - { label: Slug, name: slug, widget: hidden, default: "/" }
              - { label: Text, name: text, widget: markdown }
              - { label: Button text, name: buttonText, widget: text }
          - label: 'Work heading'
            required: true
            name: 'workHeading'
            widget: 'object'
            fields:
              - { label: Left, name: left, widget: string }
              - { label: Right, name: right, widget: string }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }
      #
      # Cases page
      #
      - file: 'content/pages/cases.md'
        label: 'Cases'
        name: 'cases'
        fields:
          - { label: Titel, name: title, widget: string, required: true }
          - { label: Excerpt, name: excerpt, widget: text }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }
      #
      # Cases page
      #
      - file: 'content/pages/about.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: Titel, name: title, widget: string, required: true }
          - label: 'First section'
            required: true
            name: 'firstSection'
            widget: 'object'
            fields:
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: 'Second section'
            required: true
            name: 'secondSection'
            widget: 'object'
            fields:
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - { label: Footer image, name: footerImage, widget: image }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

  # ----------------------------------------------------------------------------
  # Cases
  # ----------------------------------------------------------------------------
  - name: 'cases'
    label: "Cases"
    editor:
      preview: true
    folder: content/cases
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: Titel, name: title, widget: string, required: true }
      - {
        label: Date,
        name: date,
        widget: date,
        format: 'MM/DD/YYYY',
        required: true,
      }
      - { label: Featured image, name: featuredImage, widget: image }
      - label: 'List'
        required: true
        name: 'list'
        widget: 'object'
        fields:
          - { label: Url, name: url, widget: string }
          - label: "Employer"
            name: "employer"
            widget: "select"
            options:
              - { label: "Personal project", value: "personalProject" }
              - { label: "Oddessey Solutions", value: "oddesseySolutions" }
              - { label: "Thrive Web", value: "thriveWeb" }
            default: ["Personal project"]
          - label: "Project type"
            name: "projectType"
            widget: "select"
            options:
              - { label: "WordPress", value: "wordpress" }
              - { label: "React", value: "react" }
            default: ["WordPress"]
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Device preview, name: devicePreview, widget: image }
      - { label: Content, name: content, widget: markdown }


      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - {
              label: Noindex,
              name: noindex,
              widget: boolean,
              required: false,
            }
